-- MySQL Script generated by MySQL Workbench
-- Wed Sep 11 21:11:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ordems_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ordems_db` ;

-- -----------------------------------------------------
-- Schema ordems_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ordems_db` ;
USE `ordems_db` ;

-- -----------------------------------------------------
-- Table `ordems_db`.`sku`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordems_db`.`sku` ;

CREATE TABLE IF NOT EXISTS `ordems_db`.`sku` (
  `id_sku` INT(11) NOT NULL AUTO_INCREMENT,
  `data_cad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` INT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_sku`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordems_db`.`peca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordems_db`.`peca` ;

CREATE TABLE IF NOT EXISTS `ordems_db`.`peca` (
  `id_peca` INT(11) NOT NULL AUTO_INCREMENT,
  `data_cad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `nm_peca` VARCHAR(40) NOT NULL,
  `id_fornecedor` INT(11) NOT NULL,
  `vl_custo` FLOAT(6,2) NOT NULL,
  `vl_venda` FLOAT(6,2) NOT NULL,
  `sku_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_peca`),
  INDEX `fk_peca_sku1_idx` (`sku_id` ASC),
  CONSTRAINT `fk_peca_sku1`
    FOREIGN KEY (`sku_id`)
    REFERENCES `ordems_db`.`sku` (`id_sku`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordems_db`.`tipo_faq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordems_db`.`tipo_faq` ;

CREATE TABLE IF NOT EXISTS `ordems_db`.`tipo_faq` (
  `id_tipo_faq` INT(11) NOT NULL AUTO_INCREMENT,
  `data_cad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`id_tipo_faq`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordems_db`.`faq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordems_db`.`faq` ;

CREATE TABLE IF NOT EXISTS `ordems_db`.`faq` (
  `id_faq` INT(11) NOT NULL AUTO_INCREMENT,
  `data_cad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `titulo` VARCHAR(40) NOT NULL,
  `descricao` TEXT NOT NULL,
  `tipo_faq_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_faq`),
  INDEX `fk_faq_tipo_faq1_idx` (`tipo_faq_id` ASC),
  CONSTRAINT `fk_faq_tipo_faq1`
    FOREIGN KEY (`tipo_faq_id`)
    REFERENCES `ordems_db`.`tipo_faq` (`id_tipo_faq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordems_db`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordems_db`.`usuario` ;

CREATE TABLE IF NOT EXISTS `ordems_db`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `data_cad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `nm_usuario` VARCHAR(60) NOT NULL,
  `cargo` VARCHAR(20) NULL DEFAULT NULL,
  `departamento` VARCHAR(20) NOT NULL,
  `matricula` INT(11) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  `status` INT(1) NOT NULL DEFAULT '1',
  `faq_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `fk_usuario_faq1_idx` (`faq_id` ASC),
  CONSTRAINT `fk_usuario_faq1`
    FOREIGN KEY (`faq_id`)
    REFERENCES `ordems_db`.`faq` (`id_faq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1004
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordems_db`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordems_db`.`perfil` ;

CREATE TABLE IF NOT EXISTS `ordems_db`.`perfil` (
  `id_perfil` INT(11) NOT NULL AUTO_INCREMENT,
  `nivel_perfil` INT(1) NOT NULL,
  `nm_perfil` VARCHAR(40) NOT NULL,
  `usuario_id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_perfil`, `usuario_id_usuario`),
  INDEX `fk_perfil_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_perfil_usuario`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `ordems_db`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordems_db`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordems_db`.`cliente` ;

CREATE TABLE IF NOT EXISTS `ordems_db`.`cliente` (
  `id_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `data_cad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_nasc` DATE NOT NULL,
  `data_uedit` DATE NULL DEFAULT NULL,
  `nm_cliente` VARCHAR(60) NOT NULL,
  `tipo_cliente` INT(1) NOT NULL DEFAULT '1',
  `doc_num` VARCHAR(15) NOT NULL,
  `rg_ie` VARCHAR(15) NULL DEFAULT NULL,
  `celular` VARCHAR(15) NOT NULL,
  `fone_re` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(40) NOT NULL,
  `pes_contato` VARCHAR(20) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `endereco` VARCHAR(60) NULL DEFAULT NULL,
  `numero` VARCHAR(6) NULL DEFAULT NULL,
  `complemento` VARCHAR(40) NULL DEFAULT NULL,
  `bairro` VARCHAR(40) NULL DEFAULT NULL,
  `cidade` VARCHAR(40) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `doc_num_UNIQUE` (`doc_num` ASC),
  INDEX `fk_clientes_as_usuario` (`usuario_id` ASC),
  CONSTRAINT `fk_clientes_as_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ordems_db`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordems_db`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordems_db`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `ordems_db`.`fornecedor` (
  `id_fornecedor` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(11) NOT NULL,
  `data_cad` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `nm_fornecedor` VARCHAR(60) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `num_documento` VARCHAR(14) NOT NULL,
  `ie` VARCHAR(15) NULL DEFAULT NULL,
  `celular` VARCHAR(15) NOT NULL,
  `fone_fixo` VARCHAR(15) NULL DEFAULT NULL,
  `pes_contato` VARCHAR(20) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `endereco` VARCHAR(60) NULL DEFAULT NULL,
  `numero` VARCHAR(6) NULL DEFAULT NULL,
  `complemento` VARCHAR(40) NULL DEFAULT NULL,
  `bairro` VARCHAR(40) NULL DEFAULT NULL,
  `cidade` VARCHAR(40) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_fornecedor`),
  INDEX `fk_fornecedor_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_fornecedor_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ordems_db`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordems_db`.`os`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordems_db`.`os` ;

CREATE TABLE IF NOT EXISTS `ordems_db`.`os` (
  `id_os` INT(11) NOT NULL AUTO_INCREMENT,
  `cliente_id` INT(11) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  `data_os` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_previsao` DATE NOT NULL,
  `data_pronto` DATE NULL DEFAULT NULL,
  `data_entrega` DATE NULL DEFAULT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `modelo` VARCHAR(20) NOT NULL,
  `marca` VARCHAR(20) NOT NULL,
  `cor` VARCHAR(20) NOT NULL,
  `serie` VARCHAR(20) NOT NULL,
  `garantia` INT(1) NOT NULL DEFAULT '1',
  `info_cliente` VARCHAR(250) NOT NULL,
  `info_tecnico` VARCHAR(250) NOT NULL,
  `info_entrega` VARCHAR(250) NOT NULL,
  `info_interna` VARCHAR(250) NOT NULL,
  `status` INT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_os`),
  INDEX `fk_clientes_as_os` (`cliente_id` ASC),
  INDEX `fk_os_as_usuario` (`usuario_id` ASC),
  CONSTRAINT `fk_os_as_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `ordems_db`.`cliente` (`id_cliente`),
  CONSTRAINT `fk_os_as_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ordems_db`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordems_db`.`relaciona_fornecedor_peca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordems_db`.`relaciona_fornecedor_peca` ;

CREATE TABLE IF NOT EXISTS `ordems_db`.`relaciona_fornecedor_peca` (
  `id_fornecedor` INT(11) NULL DEFAULT NULL,
  `id_peca` INT(11) NULL DEFAULT NULL,
  INDEX `fk_relaciona_fornecedor_usuario_1_idx` (`id_fornecedor` ASC, `id_peca` ASC),
  INDEX `fk_relaciona_fornecedor_usuario_2_idx` (`id_peca` ASC),
  CONSTRAINT `fk_relaciona_fornecedor_peca_1`
    FOREIGN KEY (`id_peca`)
    REFERENCES `ordems_db`.`fornecedor` (`id_fornecedor`),
  CONSTRAINT `fk_relaciona_fornecedor_peca_2`
    FOREIGN KEY (`id_fornecedor`)
    REFERENCES `ordems_db`.`peca` (`id_peca`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ordems_db`.`relaciona_os_peca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ordems_db`.`relaciona_os_peca` ;

CREATE TABLE IF NOT EXISTS `ordems_db`.`relaciona_os_peca` (
  `peca_id` INT(11) NULL DEFAULT NULL,
  `os_id` INT(11) NULL,
  INDEX `fk_relaciona_fornecedor_usuario_1_idx` (`peca_id` ASC),
  INDEX `fk_relaciona_os_peca_os1_idx` (`os_id` ASC),
  CONSTRAINT `fk_relaciona_fornecedor_peca_20`
    FOREIGN KEY (`peca_id`)
    REFERENCES `ordems_db`.`peca` (`id_peca`),
  CONSTRAINT `fk_relaciona_os_peca_os1`
    FOREIGN KEY (`os_id`)
    REFERENCES `ordems_db`.`os` (`id_os`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
