-- MySQL Script generated by MySQL Workbench
-- Thu Aug  6 00:07:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema wwlink_ordems
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS wwlink_ordems ;

-- -----------------------------------------------------
-- Schema wwlink_ordems
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS wwlink_ordems DEFAULT CHARACTER SET latin1 ;
USE wwlink_ordems ;

-- -----------------------------------------------------
-- Table wwlink_ordems.usuario
-- -----------------------------------------------------
DROP TABLE IF EXISTS wwlink_ordems.usuario ;

CREATE TABLE IF NOT EXISTS wwlink_ordems.usuario (
  id_usuario INT(11) NOT NULL AUTO_INCREMENT,
  data_cad TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  nm_usuario VARCHAR(60) NULL DEFAULT NULL,
  cargo VARCHAR(20) NULL DEFAULT NULL,
  departamento VARCHAR(20) NULL DEFAULT NULL,
  matricula VARCHAR(11) NULL DEFAULT NULL,
  login VARCHAR(20) NULL DEFAULT NULL,
  senha VARCHAR(60) NULL DEFAULT NULL,
  status INT(1) NULL DEFAULT '1',
  PRIMARY KEY (id_usuario))
ENGINE = InnoDB
AUTO_INCREMENT = 1017
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table wwlink_ordems.cliente
-- -----------------------------------------------------
DROP TABLE IF EXISTS wwlink_ordems.cliente ;

CREATE TABLE IF NOT EXISTS wwlink_ordems.cliente (
  id_cliente INT(11) NOT NULL AUTO_INCREMENT,
  usuario_id INT(11) NULL DEFAULT NULL,
  data_cad TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  data_nasc VARCHAR(14) NULL DEFAULT NULL,
  data_uedit VARCHAR(14) NULL DEFAULT NULL,
  nm_cliente VARCHAR(60) NULL DEFAULT NULL,
  tipo_cliente INT(1) NULL DEFAULT '1',
  doc_num VARCHAR(14) NULL DEFAULT NULL,
  rg_ie VARCHAR(15) NULL DEFAULT NULL,
  celular VARCHAR(15) NULL DEFAULT NULL,
  fone_re VARCHAR(15) NULL DEFAULT NULL,
  email VARCHAR(40) NULL DEFAULT NULL,
  pes_contato VARCHAR(20) NULL DEFAULT NULL,
  cep VARCHAR(10) NULL DEFAULT NULL,
  endereco VARCHAR(60) NULL DEFAULT NULL,
  numero VARCHAR(6) NULL DEFAULT NULL,
  complemento VARCHAR(40) NULL DEFAULT NULL,
  bairro VARCHAR(40) NULL DEFAULT NULL,
  cidade VARCHAR(40) NULL DEFAULT NULL,
  estado VARCHAR(2) NULL DEFAULT NULL,
  usuario_id_usuario INT(11) NOT NULL,
  PRIMARY KEY (id_cliente, usuario_id_usuario),
  CONSTRAINT fk_cliente_usuario1
    FOREIGN KEY (usuario_id_usuario)
    REFERENCES wwlink_ordems.usuario (id_usuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;

CREATE INDEX fk_usuario ON wwlink_ordems.cliente (usuario_id ASC);

CREATE INDEX fk_cliente_usuario1_idx ON wwlink_ordems.cliente (usuario_id_usuario ASC);


-- -----------------------------------------------------
-- Table wwlink_ordems.tipo_faq
-- -----------------------------------------------------
DROP TABLE IF EXISTS wwlink_ordems.tipo_faq ;

CREATE TABLE IF NOT EXISTS wwlink_ordems.tipo_faq (
  id_tipo_faq INT(11) NOT NULL AUTO_INCREMENT,
  data_cad TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  descricao TEXT NOT NULL,
  PRIMARY KEY (id_tipo_faq))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table wwlink_ordems.faq
-- -----------------------------------------------------
DROP TABLE IF EXISTS wwlink_ordems.faq ;

CREATE TABLE IF NOT EXISTS wwlink_ordems.faq (
  id INT(11) NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(80) NULL DEFAULT NULL,
  descricao VARCHAR(300) NULL DEFAULT '',
  image VARCHAR(80) NULL DEFAULT NULL,
  tipo INT(80) NULL DEFAULT NULL,
  tipo_faq_id_tipo_faq INT(11) NOT NULL,
  usuario_id_usuario INT(11) NOT NULL,
  PRIMARY KEY (id, tipo_faq_id_tipo_faq, usuario_id_usuario),
  CONSTRAINT fk_faq_tipo_faq1
    FOREIGN KEY (tipo_faq_id_tipo_faq)
    REFERENCES wwlink_ordems.tipo_faq (id_tipo_faq)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_faq_usuario1
    FOREIGN KEY (usuario_id_usuario)
    REFERENCES wwlink_ordems.usuario (id_usuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_bin;

CREATE INDEX fk_tipo ON wwlink_ordems.faq (tipo ASC);

CREATE INDEX fk_faq_tipo_faq1_idx ON wwlink_ordems.faq (tipo_faq_id_tipo_faq ASC);

CREATE INDEX fk_faq_usuario1_idx ON wwlink_ordems.faq (usuario_id_usuario ASC);


-- -----------------------------------------------------
-- Table wwlink_ordems.fornecedor
-- -----------------------------------------------------
DROP TABLE IF EXISTS wwlink_ordems.fornecedor ;

CREATE TABLE IF NOT EXISTS wwlink_ordems.fornecedor (
  id_fornecedor INT(11) NOT NULL AUTO_INCREMENT,
  usuario_id INT(11) NULL DEFAULT NULL,
  data_cad TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  nm_fornecedor VARCHAR(60) NULL DEFAULT NULL,
  email VARCHAR(60) NULL DEFAULT NULL,
  doc_num VARCHAR(14) NULL DEFAULT NULL,
  rg_ie VARCHAR(15) NULL DEFAULT NULL,
  celular VARCHAR(15) NULL DEFAULT NULL,
  fone_re VARCHAR(15) NULL DEFAULT NULL,
  pes_contato VARCHAR(20) NULL DEFAULT NULL,
  cep VARCHAR(10) NULL DEFAULT NULL,
  endereco VARCHAR(60) NULL DEFAULT NULL,
  numero VARCHAR(6) NULL DEFAULT NULL,
  complemento VARCHAR(40) NULL DEFAULT NULL,
  bairro VARCHAR(40) NULL DEFAULT NULL,
  cidade VARCHAR(40) NULL DEFAULT NULL,
  estado VARCHAR(2) NULL DEFAULT NULL,
  tipo_fornecedor INT(1) NULL DEFAULT NULL,
  usuario_id_usuario INT(11) NOT NULL,
  PRIMARY KEY (id_fornecedor, usuario_id_usuario),
  CONSTRAINT fk_fornecedor_usuario1
    FOREIGN KEY (usuario_id_usuario)
    REFERENCES wwlink_ordems.usuario (id_usuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;

CREATE INDEX fk_fornecedor_usuario1_idx ON wwlink_ordems.fornecedor (usuario_id_usuario ASC);


-- -----------------------------------------------------
-- Table wwlink_ordems.servico
-- -----------------------------------------------------
DROP TABLE IF EXISTS wwlink_ordems.servico ;

CREATE TABLE IF NOT EXISTS wwlink_ordems.servico (
  id_servico INT(11) NOT NULL,
  nm_servico VARCHAR(80) CHARACTER SET 'utf8' NOT NULL,
  vl_servico FLOAT(6,2) NOT NULL,
  descricao VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  estoque INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (id_servico))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table wwlink_ordems.os_status
-- -----------------------------------------------------
DROP TABLE IF EXISTS wwlink_ordems.os_status ;

CREATE TABLE IF NOT EXISTS wwlink_ordems.os_status (
  id_status INT(11) NOT NULL AUTO_INCREMENT,
  status VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (id_status))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table wwlink_ordems.os
-- -----------------------------------------------------
DROP TABLE IF EXISTS wwlink_ordems.os ;

CREATE TABLE IF NOT EXISTS wwlink_ordems.os (
  id_os INT(11) NOT NULL AUTO_INCREMENT,
  cliente_id INT(11) NULL DEFAULT NULL,
  usuario_id INT(11) NULL DEFAULT NULL,
  data_os TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  data_previsao VARCHAR(20) NULL DEFAULT NULL,
  data_pronto VARCHAR(20) NULL DEFAULT NULL,
  data_entrega VARCHAR(20) NULL DEFAULT NULL,
  tipo VARCHAR(20) NULL DEFAULT NULL,
  modelo VARCHAR(20) NULL DEFAULT NULL,
  marca VARCHAR(20) NULL DEFAULT NULL,
  cor VARCHAR(20) NULL DEFAULT NULL,
  serie VARCHAR(20) NULL DEFAULT NULL,
  garantia INT(1) NULL DEFAULT '1',
  info_cliente VARCHAR(250) NULL DEFAULT NULL,
  info_tecnico VARCHAR(250) NULL DEFAULT NULL,
  info_entrega VARCHAR(250) NULL DEFAULT NULL,
  info_interna VARCHAR(250) NULL DEFAULT NULL,
  status_id INT(11) NULL DEFAULT '1',
  peca_id INT(11) NULL DEFAULT NULL,
  servico_id INT(11) NULL DEFAULT NULL,
  valorTotal FLOAT(6,2) NULL DEFAULT NULL,
  usuario_id_usuario INT(11) NOT NULL,
  cliente_id_cliente INT(11) NOT NULL,
  servico_id_servico INT(11) NOT NULL,
  os_status_id_status INT(11) NOT NULL,
  PRIMARY KEY (id_os, usuario_id_usuario, cliente_id_cliente, servico_id_servico, os_status_id_status),
  CONSTRAINT fk_os_usuario1
    FOREIGN KEY (usuario_id_usuario)
    REFERENCES wwlink_ordems.usuario (id_usuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_os_cliente1
    FOREIGN KEY (cliente_id_cliente)
    REFERENCES wwlink_ordems.cliente (id_cliente)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_os_servico1
    FOREIGN KEY (servico_id_servico)
    REFERENCES wwlink_ordems.servico (id_servico)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_os_os_status1
    FOREIGN KEY (os_status_id_status)
    REFERENCES wwlink_ordems.os_status (id_status)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;

CREATE INDEX fk_peca ON wwlink_ordems.os (peca_id ASC) ;

CREATE INDEX fk_servico ON wwlink_ordems.os (servico_id ASC) ;

CREATE INDEX fk_status ON wwlink_ordems.os (status_id ASC) ;

CREATE INDEX fk_cliente ON wwlink_ordems.os (cliente_id ASC) ;

CREATE INDEX fk_usuario ON wwlink_ordems.os (usuario_id ASC) ;

CREATE INDEX fk_os_usuario1_idx ON wwlink_ordems.os (usuario_id_usuario ASC) ;

CREATE INDEX fk_os_cliente1_idx ON wwlink_ordems.os (cliente_id_cliente ASC) ;

CREATE INDEX fk_os_servico1_idx ON wwlink_ordems.os (servico_id_servico ASC) ;

CREATE INDEX fk_os_os_status1_idx ON wwlink_ordems.os (os_status_id_status ASC) ;


-- -----------------------------------------------------
-- Table wwlink_ordems.peca
-- -----------------------------------------------------
DROP TABLE IF EXISTS wwlink_ordems.peca ;

CREATE TABLE IF NOT EXISTS wwlink_ordems.peca (
  id_peca INT(11) NOT NULL AUTO_INCREMENT,
  data_cad TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  nm_peca VARCHAR(40) NOT NULL,
  vl_custo FLOAT(6,2) NOT NULL,
  vl_venda FLOAT(6,2) NOT NULL,
  estoque INT(11) NULL DEFAULT NULL,
  entrada INT(11) NULL DEFAULT NULL,
  saida INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (id_peca))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table wwlink_ordems.perfil
-- -----------------------------------------------------
DROP TABLE IF EXISTS wwlink_ordems.perfil ;

CREATE TABLE IF NOT EXISTS wwlink_ordems.perfil (
  id_perfil INT(11) NOT NULL AUTO_INCREMENT,
  nivel_perfil INT(1) NOT NULL,
  nm_perfil VARCHAR(40) NOT NULL,
  PRIMARY KEY (id_perfil))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table wwlink_ordems.recebimento
-- -----------------------------------------------------
DROP TABLE IF EXISTS wwlink_ordems.recebimento ;

CREATE TABLE IF NOT EXISTS wwlink_ordems.recebimento (
  id_recebimento INT(11) NOT NULL,
  usuario_id INT(11) NULL DEFAULT NULL,
  cliente_id INT(11) NULL DEFAULT NULL,
  os_id INT(11) NULL DEFAULT NULL,
  formaPagamento FLOAT(6,2) NULL DEFAULT NULL,
  valorRecebimento FLOAT(6,2) NULL DEFAULT NULL,
  statusRecebimento TINYINT(1) NULL DEFAULT NULL,
  cliente_id_cliente INT(11) NOT NULL,
  cliente_usuario_id_usuario INT(11) NOT NULL,
  usuario_id_usuario INT(11) NOT NULL,
  PRIMARY KEY (id_recebimento, cliente_id_cliente, cliente_usuario_id_usuario, usuario_id_usuario),
  CONSTRAINT fk_recebimento_cliente1
    FOREIGN KEY (cliente_id_cliente , cliente_usuario_id_usuario)
    REFERENCES wwlink_ordems.cliente (id_cliente , usuario_id_usuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_recebimento_usuario1
    FOREIGN KEY (usuario_id_usuario)
    REFERENCES wwlink_ordems.usuario (id_usuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

CREATE INDEX fk_cliente ON wwlink_ordems.recebimento (cliente_id ASC) ;

CREATE INDEX fk_usurio ON wwlink_ordems.recebimento (usuario_id ASC) ;

CREATE INDEX fk_os ON wwlink_ordems.recebimento (os_id ASC) ;

CREATE INDEX fk_recebimento_cliente1_idx ON wwlink_ordems.recebimento (cliente_id_cliente ASC, cliente_usuario_id_usuario ASC) ;

CREATE INDEX fk_recebimento_usuario1_idx ON wwlink_ordems.recebimento (usuario_id_usuario ASC) ;


-- -----------------------------------------------------
-- Table wwlink_ordems.peca_has_os
-- -----------------------------------------------------
DROP TABLE IF EXISTS wwlink_ordems.peca_has_os ;

CREATE TABLE IF NOT EXISTS wwlink_ordems.peca_has_os (
  peca_id_peca INT(11) NOT NULL,
  os_id_os INT(11) NOT NULL,
  PRIMARY KEY (peca_id_peca, os_id_os),
  CONSTRAINT fk_peca_has_os_peca
    FOREIGN KEY (peca_id_peca)
    REFERENCES wwlink_ordems.peca (id_peca)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_peca_has_os_os1
    FOREIGN KEY (os_id_os)
    REFERENCES wwlink_ordems.os (id_os)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX fk_peca_has_os_os1_idx ON wwlink_ordems.peca_has_os (os_id_os ASC) ;

CREATE INDEX fk_peca_has_os_peca_idx ON wwlink_ordems.peca_has_os (peca_id_peca ASC) ;


-- -----------------------------------------------------
-- Table wwlink_ordems.perfil_has_usuario
-- -----------------------------------------------------
DROP TABLE IF EXISTS wwlink_ordems.perfil_has_usuario ;

CREATE TABLE IF NOT EXISTS wwlink_ordems.perfil_has_usuario (
  perfil_id_perfil INT(11) NOT NULL,
  usuario_id_usuario INT(11) NOT NULL,
  PRIMARY KEY (perfil_id_perfil, usuario_id_usuario),
  CONSTRAINT fk_perfil_has_usuario_perfil1
    FOREIGN KEY (perfil_id_perfil)
    REFERENCES wwlink_ordems.perfil (id_perfil)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_perfil_has_usuario_usuario1
    FOREIGN KEY (usuario_id_usuario)
    REFERENCES wwlink_ordems.usuario (id_usuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX fk_perfil_has_usuario_usuario1_idx ON wwlink_ordems.perfil_has_usuario (usuario_id_usuario ASC) ;

CREATE INDEX fk_perfil_has_usuario_perfil1_idx ON wwlink_ordems.perfil_has_usuario (perfil_id_perfil ASC) ;


-- -----------------------------------------------------
-- Table wwlink_ordems.peca_has_fornecedor
-- -----------------------------------------------------
DROP TABLE IF EXISTS wwlink_ordems.peca_has_fornecedor ;

CREATE TABLE IF NOT EXISTS wwlink_ordems.peca_has_fornecedor (
  peca_id_peca INT(11) NOT NULL,
  fornecedor_id_fornecedor INT(11) NOT NULL,
  PRIMARY KEY (peca_id_peca, fornecedor_id_fornecedor),
  CONSTRAINT fk_peca_has_fornecedor_peca1
    FOREIGN KEY (peca_id_peca)
    REFERENCES wwlink_ordems.peca (id_peca)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_peca_has_fornecedor_fornecedor1
    FOREIGN KEY (fornecedor_id_fornecedor)
    REFERENCES wwlink_ordems.fornecedor (id_fornecedor)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX fk_peca_has_fornecedor_fornecedor1_idx ON wwlink_ordems.peca_has_fornecedor (fornecedor_id_fornecedor ASC) ;

CREATE INDEX fk_peca_has_fornecedor_peca1_idx ON wwlink_ordems.peca_has_fornecedor (peca_id_peca ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
