/*
 * To change this template, choose Tools | Templates


 * and open the template in the editor.
 */

/*
 *
 * Created on 03/10/2016, 14:47:58
 * Fonte e créditos.
 * https://www.republicavirtual.com.br/cep/index.php
 */
package view;

import dao.APIConsultaCEP;
import model.Fornecedor;
import model.TabelaFornecedor;

import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

import controller.FornecedorController;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.SwingConstants;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ScrollPaneConstants;
import java.awt.FlowLayout;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;

import javax.swing.JButton;

/**
 *
 * @author ADM
 */
public class FornecedorView extends javax.swing.JFrame implements ActionListener   {

    /** Creates new form CEP */
    public FornecedorView() {
    	setTitle("Cadastrode Fornecedores");
    	
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	painelBotoes = new JPanel();
        painelBotoes.setLayout(new FlowLayout());
        
       
        
        getContentPane().add(painelBotoes, BorderLayout.SOUTH);
        
      


        enderecoPanel = new javax.swing.JPanel();
        enderecoPanel.setBorder(new LineBorder(new Color(0, 0, 0)));
        logradouroLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        ruaField = new javax.swing.JTextField();
        bairroLabel = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        bairroField = new javax.swing.JTextField();
        cidadeLabel = new javax.swing.JLabel();
        cidadeField = new javax.swing.JTextField();
        ufLabel = new javax.swing.JLabel();
        estadoComboBox = new javax.swing.JComboBox();
        cepLabel = new javax.swing.JLabel();
        cepField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        

        try {
            cepField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cepField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TCEPKeyReleased(evt);
            }
        });
//        
        cepLabel.setText("CEP");
        
        logradouroLabel.setText("Logradouro");

        jTextField1.setText("jTextField1");

        bairroLabel.setText("Bairro");

        jTextField2.setText("jTextField2");

        cidadeLabel.setText("Cidade");

        ufLabel.setText("UF");

        estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        
        complementoField = new JTextField();
        complementoField.setColumns(10);
        
        JLabel numeroLabel = new JLabel();
        numeroLabel.setText("N\u00FAmero");
        
        numeroField = new JTextField();
        
        JLabel label_6 = new JLabel();
        label_6.setText("Bairro");


        javax.swing.GroupLayout gl_enderecoPanel = new javax.swing.GroupLayout(enderecoPanel);
        gl_enderecoPanel.setHorizontalGroup(
        	gl_enderecoPanel.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_enderecoPanel.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_enderecoPanel.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_enderecoPanel.createSequentialGroup()
        					.addComponent(bairroField, GroupLayout.PREFERRED_SIZE, 174, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addGroup(gl_enderecoPanel.createSequentialGroup()
        					.addGroup(gl_enderecoPanel.createParallelGroup(Alignment.TRAILING)
        						.addComponent(bairroLabel, Alignment.LEADING)
        						.addComponent(cepLabel, Alignment.LEADING)
        						.addComponent(cepField, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 129, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(gl_enderecoPanel.createParallelGroup(Alignment.TRAILING)
        						.addGroup(gl_enderecoPanel.createSequentialGroup()
        							.addGap(53)
        							.addGroup(gl_enderecoPanel.createParallelGroup(Alignment.LEADING)
        								.addComponent(cidadeField, GroupLayout.PREFERRED_SIZE, 254, GroupLayout.PREFERRED_SIZE)
        								.addComponent(cidadeLabel))
        							.addGap(10)
        							.addGroup(gl_enderecoPanel.createParallelGroup(Alignment.LEADING)
        								.addComponent(ufLabel)
        								.addComponent(estadoComboBox, 0, 170, Short.MAX_VALUE)))
        						.addGroup(Alignment.LEADING, gl_enderecoPanel.createSequentialGroup()
        							.addGap(10)
        							.addGroup(gl_enderecoPanel.createParallelGroup(Alignment.LEADING)
        								.addComponent(ruaField, GroupLayout.PREFERRED_SIZE, 297, GroupLayout.PREFERRED_SIZE)
        								.addComponent(logradouroLabel))
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(gl_enderecoPanel.createParallelGroup(Alignment.LEADING)
        								.addComponent(numeroLabel, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
        								.addComponent(complementoField, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE))
        							.addGap(6)
        							.addGroup(gl_enderecoPanel.createParallelGroup(Alignment.LEADING)
        								.addComponent(label_6, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        								.addComponent(numeroField, GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))))
        					.addGap(10))))
        );
        gl_enderecoPanel.setVerticalGroup(
        	gl_enderecoPanel.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_enderecoPanel.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_enderecoPanel.createParallelGroup(Alignment.TRAILING)
        				.addGroup(gl_enderecoPanel.createSequentialGroup()
        					.addGroup(gl_enderecoPanel.createParallelGroup(Alignment.BASELINE)
        						.addComponent(cepLabel)
        						.addComponent(logradouroLabel)
        						.addComponent(numeroLabel))
        					.addGap(3)
        					.addGroup(gl_enderecoPanel.createParallelGroup(Alignment.BASELINE)
        						.addComponent(cepField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(ruaField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(complementoField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(gl_enderecoPanel.createSequentialGroup()
        					.addComponent(label_6)
        					.addGap(6)
        					.addComponent(numeroField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(11)
        			.addGroup(gl_enderecoPanel.createParallelGroup(Alignment.BASELINE)
        				.addComponent(bairroLabel)
        				.addComponent(cidadeLabel)
        				.addComponent(ufLabel))
        			.addGap(6)
        			.addGroup(gl_enderecoPanel.createParallelGroup(Alignment.BASELINE)
        				.addComponent(bairroField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(cidadeField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(estadoComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(16, Short.MAX_VALUE))
        );
        enderecoPanel.setLayout(gl_enderecoPanel);
        
        JPanel panel = new JPanel();
        panel.setLayout(null);
        panel.setBorder(new LineBorder(Color.LIGHT_GRAY));
        
        pes_contatoField = new JTextField(20);
        pes_contatoField.setBounds(436, 51, 186, 20);
        panel.add(pes_contatoField);
        
        JLabel pes_contatolabel = new JLabel("Pessoa de Contato");
        pes_contatolabel.setBounds(436, 37, 166, 14);
        panel.add(pes_contatolabel);
        
        emailField = new JTextField(40);
        emailField.setBounds(10, 138, 382, 20);
        panel.add(emailField);
        
        JLabel emailLabel = new JLabel("Email");
        emailLabel.setBounds(10, 126, 368, 14);
        panel.add(emailLabel);
        
        JRadioButton cpfRadio = new JRadioButton("CPF");
        cpfRadio.setHorizontalAlignment(SwingConstants.RIGHT);
        cpfRadio.setBounds(79, 7, 50, 23);
        panel.add(cpfRadio);
        
        JRadioButton cnpjRadio = new JRadioButton("CNPJ");
        cnpjRadio.setSelected(true);
        cnpjRadio.setHorizontalAlignment(SwingConstants.RIGHT);
        cnpjRadio.setBounds(131, 7, 56, 23);
        panel.add(cnpjRadio);
        
        rgieField = new JTextField(20);
        rgieField.setBounds(193, 8, 199, 20);
        panel.add(rgieField);
        
        JLabel rgielabel = new JLabel("RG/IE");
        rgielabel.setHorizontalAlignment(SwingConstants.RIGHT);
        rgielabel.setBounds(376, 11, 50, 14);
        panel.add(rgielabel);
        
        nomeField = new JTextField(20);
        nomeField.setBounds(436, 7, 186, 20);
        panel.add(nomeField);
        
        JLabel nomelabel = new JLabel("Nome / Raz\u00E3o");
        nomelabel.setBounds(10, 37, 338, 14);
        panel.add(nomelabel);
        
        docField = new JTextField(40);
        docField.setBounds(10, 51, 382, 20);
        panel.add(docField);
        
        JLabel documentolabel = new JLabel("Documento");
        documentolabel.setBounds(10, 11, 63, 14);
        panel.add(documentolabel);
        
        
        telefoneField = new JTextField(20);
        telefoneField.setBounds(10, 95, 186, 20);
        panel.add(telefoneField);
        
        JLabel telefonelabel = new JLabel("Telefone");
        telefonelabel.setBounds(10, 82, 166, 14);
        panel.add(telefonelabel);
        
        celularField = new JTextField(20);
        celularField.setBounds(206, 95, 186, 20);
        panel.add(celularField);
        
        JLabel celularlabel = new JLabel("Celular");
        celularlabel.setBounds(206, 82, 162, 14);
        panel.add(celularlabel);
        
        JScrollPane scrollPane = new JScrollPane();
        scrollPane.setViewportBorder(new LineBorder(Color.LIGHT_GRAY));
        scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        
        painelBotoes = new JPanel();
        painelBotoes.setLayout(new FlowLayout());
        
        botaoSalvar = new JButton("Salvar");
        botaoEditar = new JButton("Editar");
        botaoExcluir = new JButton("Excluir");
        botaoCancelar = new JButton("Cancelar");
        
        painelBotoes.add(botaoSalvar);        
        painelBotoes.add(botaoEditar);
        painelBotoes.add(botaoExcluir);
        painelBotoes.add(botaoCancelar);
        
        botaoSalvar.addActionListener(this);
        botaoSalvar.setActionCommand("salvar");
        
        botaoEditar.addActionListener(this);
        botaoEditar.setActionCommand("editar");
        
        botaoExcluir.addActionListener(this);
        botaoExcluir.setActionCommand("excluir");
        
        botaoCancelar.addActionListener(this);
        botaoCancelar.setActionCommand("cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(painelBotoes, GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        					.addContainerGap())
        				.addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(enderecoPanel, 0, 0, Short.MAX_VALUE)
        						.addComponent(panel, GroupLayout.PREFERRED_SIZE, 643, GroupLayout.PREFERRED_SIZE))
        					.addContainerGap())))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(panel, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(enderecoPanel, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(painelBotoes, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        
        getContentPane().setLayout(layout);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-693)/2, (screenSize.height-338)/2, 680, 640);
    }// </editor-fold>
    //GEN-END:initComponents

private void TCEPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCEPKeyReleased
    String cp = cepField.getText();
    cp = cp.replaceAll("\\D*", ""); //ignora qualquer coisa que nÃ£o seja numero.  
    int cont = cp.length();
    
    if(cont == 8){
     try{
     correio();
     }
     catch(Error e){
     JOptionPane.showMessageDialog(null, e); 
     }
    }// TODO add your handling code here:
}	//GEN-LAST:event_TCEPKeyReleased

    /**
     * @param args the command line arguments
    */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FornecedorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FornecedorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FornecedorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FornecedorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FornecedorView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    //GEN-BEGIN:variables
    private javax.swing.JComboBox estadoComboBox;
    private javax.swing.JTextField bairroField;
    private javax.swing.JFormattedTextField cepField;
    private javax.swing.JTextField cidadeField;
    private javax.swing.JTextField ruaField;
    private javax.swing.JLabel logradouroLabel;
    private javax.swing.JLabel bairroLabel;
    private javax.swing.JLabel cidadeLabel;
    private javax.swing.JLabel ufLabel;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JPanel enderecoPanel;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private JTextField pes_contatoField;
    
    private JTable fornecedorTable;
    TabelaFornecedor tabelaFornecedor;
    
    
  //Inicia o painel dos botoes
    JPanel painelBotoes;
    JButton botaoSalvar;
    JButton botaoCancelar;
    JButton botaoEditar;
    JButton botaoExcluir;
    
    
    private JTextField emailField;
    private JTextField rgieField;
    private JTextField nomeField;
    private JTextField docField;
    private JTextField telefoneField;
    private JTextField celularField;
    private JTextField complementoField;
    private JTextField numeroField;
    // End of variables declaration//GEN-END:variables
public  void correio() {
    
                String cep =  cepField.getText();
		
                APIConsultaCEP webServiceCep = APIConsultaCEP.searchCep(cep);

		if (webServiceCep.wasSuccessful()) {
                       
                        ruaField.setText(webServiceCep.getLogradouroFull()); 
                        bairroField.setText(webServiceCep.getBairro());                        
                        cidadeField.setText(webServiceCep.getCidade());
                        estadoComboBox.setSelectedItem( webServiceCep.getUf());

		} else {
                         JOptionPane.showMessageDialog(null, webServiceCep.getResultText());
                        
		}
			
	}
    //método para limpar tela
		private void limpaCampos() {

			nomeField.setText("");
			docField.setText("");
			rgieField.setText("");
			telefoneField.setText("");			
			celularField.setText("");
			emailField.setText("");
			pes_contatoField.setText("");
			cepField.setText("");
			ruaField.setText("");
			numeroField.setText("");
			complementoField.setText("");
			bairroField.setText("");
			cidadeField.setText("");
			estadoComboBox.setToolTipText("");
	
			this.enderecoPanel.repaint();
			//this.fornecedorPainel.repaint();
}

		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub
			
			if(e.getActionCommand().equalsIgnoreCase("salvar")) {
				
				Fornecedor f = new Fornecedor();
				
				//Tratar a ação de salvar o cliente
				
				//Trata o radio do tipo de cliente
				
				
				//Tipo
				System.out.println("Tipo: " +f.getTipo());
				//nome
				f.setNm_fornecedor(nomeField.getText());			
				//documento
				f.setDoc_num(docField.getText());			
				//RGIE
				f.setRg_ie(rgieField.getText());
				//fone fixo
				f.setFone_re(telefoneField.getText());
				//celular
				f.setCelular(celularField.getText());
				//email
				f.setEmail(emailField.getText());
				//pessoa contato
				f.setPes_contato(pes_contatoField.getText());
				//Logradouro
//				f.getApiconsutacep().setCep(cepField.getText());
//				//Logradouro
//				f.getEndereco().setRua(ruaField.getText());
//				//numero
//				f.getEndereco().setNumero(numeroField.getText());
//				//complemento
//				f.getEndereco().setComplemento(complementoField.getText());
//				//bairro
//				f.getEndereco().setTBAIRRO(TBAIRRO.getText());
//				//cidade
//				f.getEndereco().setTCIDADE(TCIDADE.getText());
//				//estado
//				f.getEndereco().setCESTADO(CESTADO.getToolTipText());
				
				Object[] opcoes = {"Salvar como novo cadastro", "Atualizar", "Limpar todos campos"};
		
				
				int op = JOptionPane.showOptionDialog(null, "Escolha uma opção para continuar", "Aviso",
				          JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
				              null, opcoes, opcoes[0]);
					
					if(op == 0) { //salvar um novo cliente
						FornecedorController controleCliente = new FornecedorController();
						try {
							if(controleCliente.cadastrarFornecedor(f) == true) {
								JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");
								tabelaFornecedor.addTodos();
								limpaCampos();
								this.repaint();
							}
							}
						 catch (SQLException e1) {
							e1.printStackTrace();
							JOptionPane.showMessageDialog(null, "Ops, houve um erro ao efetuar o cadastro!");
						}
					}
//					else if(op == 1) { //ATUALIZAR
//						f.setId(this.id);
//						FornecedorController controleFornecedor = new FornecedorController();
//						try {
//							if(controleFornecedor.atualizarFornecedor(f) == true) {
//								JOptionPane.showMessageDialog(null, "Cadastro atualizado com sucesso!");
//								tabelaFornecedor.addTodos();
//								limpaCampos();
//								this.repaint();
//							}
//						} catch (HeadlessException | SQLException e1) {
//							// TODO Auto-generated catch block
//							e1.printStackTrace();
//							JOptionPane.showMessageDialog(null, "Ops, houve um ao efetuar o cadastro!");
//						}				
//						
//					}
//					else {
//						cpfRadio.setEnabled(true);
//									
//						nm_fornecedorField.setText("");
//						docField.setText("");
//						rgieField.setText("");
//						fone_reField.setText("");			
//						celularField.setText("");
//						emailField.setText("");
//						pes_contatoField.setText("");
//						TCEP.setText("");
//						TRUA.setText("");
//						numeroField.setText("");
//						complementoField.setText("");
//						TBAIRRO.setText("");
//						TCIDADE.setText("");
//						CESTADO.setToolTipText("");
//						
//					}
//			
			}
			
		}

}

